name: Build windows executable

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'tectonic-typesetting/tectonic'
      - name: Clone vcpkg
        run: git clone https://github.com/microsoft/vcpkg
      - name: Install vcpkg
        run: .\vcpkg\bootstrap-vcpkg.bat
      - name: Set vcpkg root
        run: .\vcpkg\vcpkg integrate install
      - name: Install dependencies
        run: .\vcpkg\vcpkg install --triplet x64-windows-static fontconfig freetype harfbuzz[icu,graphite2]
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build tectonic
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
        env:
          TECTONIC_DEP_BACKEND: vcpkg
          RUSTFLAGS: "-Ctarget-feature=+crt-static"
      - name: Display
        run: dir
